courseName = "Python language"
print(len(courseName))
print(courseName[5])
print(courseName.upper())
print(courseName.lower())
print(courseName.casefold())
print("   sreeni   ".strip())
name = "   sreeni   "
print(len(name))
print(name.strip())
print(name)
print(name.lstrip())
print(name.rstrip())
print(courseName.startswith("P"))
print(courseName.endswith("y"))
print(courseName[2:6])
print(courseName[:8])
print(courseName[1:])
print(courseName.center(50))
print(courseName.capitalize())
print(courseName.index("y"))
print(courseName.count("m"))
print(courseName.isalnum())
